DROP TABLE IF EXISTS FRIENDSHIP;
DROP TABLE IF EXISTS USERS;


CREATE TABLE IF NOT EXISTS USERS(
    USER_ID INT PRIMARY KEY AUTO_INCREMENT,
    EMAIL VARCHAR(50) NOT NULL ,
    LOGIN VARCHAR(50) NOT NULL ,
    NAME VARCHAR(50) NOT NULL ,
    BIRTHDAY DATE
);

CREATE TABLE IF NOT EXISTS FRIENDSHIP(
    USER_ID1 INT NOT NULL ,
    USER_ID2 INT NOT NULL ,
    CONFIRMED BOOLEAN NOT NULL ,
    CONSTRAINT PK_FRIENDSHIP PRIMARY KEY (USER_ID1,USER_ID2),
    CONSTRAINT FK_FRIENDSHIP_USER_ID1 FOREIGN KEY (USER_ID1) REFERENCES USERS(USER_ID) ON DELETE CASCADE ,
    CONSTRAINT FK_FRIENDSHIP_USER_ID2 FOREIGN KEY (USER_ID2) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

